[package]
name = "ratatui-cellular-automaton"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.10", features = ["derive"] }
color-eyre = "0.6.3"
rand = "0.8.5"
ratatui = { version = "0.27.0", features = ["unstable-widget-ref"] }
